apiVersion: v1
kind: Namespace
metadata:
  name: nuevo-entorno
  labels:
    workshop.openshift.io/etapa: automatizacion-namespace
    workshop.openshift.io/entorno: nuevo-entorno
  annotations:
    openshift.io/description: Namespace nuevo-entorno
    openshift.io/display-name: nuevo-entorno
