apiVersion: v1
kind: LimitRange
metadata:
  name: workshop-default-limits
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 250m
        memory: 400Mi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 550m
        memory: 1500Mi
