apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../env/labels

resources:
  - namespace.yaml
  - ../env

namespace: produccion-demo-app

commonLabels:
  workshop.openshift.io/proyecto: demo-app
