apiVersion: v1
kind: ResourceQuota
metadata:
  name: workshop-quota
spec:
  hard:
    count/deployments.apps: "20"
    requests.cpu: "200m"
    limits.cpu: "1500m"
    requests.memory: 500Mi
    limits.memory: 5Gi
    requests.storage: 5Gi
    pods: "30"
