apiVersion: v1
kind: Namespace
metadata:
  name: desarrollo
  labels:
    workshop.openshift.io/etapa: automatizacion-namespace
    workshop.openshift.io/entorno: desarrollo
  annotations:
    openshift.io/description: Namespace de desarrollo del workshop
    openshift.io/display-name: Desarrollo
