apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-traffic
  description: "Deniega todo el tráfico entrante (default deny)"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
